name: Run Custom Functest
on:
  workflow_dispatch:
    inputs:
      test_name:
        required: true
        type: string

      Number of runs:
        required: true
        type: string

      Architecture:
        required: true
        type: choice
        options:
          - x64
          - ARM64

      vdut:
        required: true
        type: boolean
        default: false

jobs:
  run-functest:
    runs-on: ubuntu-latest
    container:
      image: my.image/dev:${{ github.event.inputs.architecture == 'ARM64' && 'arm64_' || '' }}latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Print values
        run: |
          echo "Test Name: ${{ github.event.inputs.test_name }}"
          echo "TYPE: ${{ github.event.inputs.type }}"
          echo "VIRTUAL: ${{ github.event.inputs.virtual }}"
          echo "Esto es test branch: ${{ github.ref }}"